### ISSUE TITLE
Login not possible

### ISSUE THREAD

**Issue by Klausoleum** [TorbenStriegel/TooGoodToGo-TelegramBot#1]
I installed the script on an RPi Buster.
At first it wasn't clear to me where I should enter the /start command.
You could add the reference to Telegram in the readme.

I can register my email address in TGTG via Telegram and also receive a verification email. Unfortunately it takes some time for the email from tgtg to arrive. Before the email arrives, a time of 120 seconds has expired in the script.
The script reports
"Exception ignored"
![grafik](https://github.com/TorbenStriegel/TooGoodToGo-TelegramBot/assets/36627883/96ad1d14-4572-40c7-9671-49751d77e07f)

After I clicked the button in the email, TGTG wrote that I was logged in and that I should go back to the app.
![grafik](https://github.com/TorbenStriegel/TooGoodToGo-TelegramBot/assets/36627883/87765124-ab0a-4591-ba95-6f93dedd47e8)

With all further commands in Telegram I get the message that I should log in first
![grafik](https://github.com/TorbenStriegel/TooGoodToGo-TelegramBot/assets/36627883/c4b0bf9f-f730-4ca6-9327-9622a5869fb3)

Where is the problem? Why can't I log in?

**Comment by Klausoleum** [comment]
OK, the problem has been solved.
I tested the basic Python TGTG project.
[tgtg-python](https://github.com/ahivert/tgtg-python)
It worked straight away.

The emails come much faster late in the evening. Faster than 120 seconds.
Now it also works via Telegram
I am now logged in

**Comment by TorbenStriegel** [comment]
Hi thanks for your feedback. I have adapted the documentation. If you have any suggestions for improvement, please feel free to submit a pull request. ;)
